application - Added basic graphics system with VisualizationArea
waterloo-rocketry/topside pull request #42
Opened 2020-06-16 17:08 UTC by Code-Titan

1. Introduced a graphical component inside PlumbingPane of type QQuickItem which can handle graphics

2. Coded in a working version into the main application using the layout_test make_engine function

3. Expanded gitignore to include my local project files

2020-06-16 23:06 UTC, jacobdeery reviewed
Cool, thanks for getting this proof of concept together so quickly!

As a general comments, the typical format for the commit message would be `application: Add basic graphics system with VisualizationArea`. Note the change to the imperative ("Add" vs "Added") and the colon instead of a dash. I would also likely shorted `application` to just `app`.

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-:-M9zJKu79JsRzJJVfGYx:b-8dhy5k)* status: 1 of 5 files reviewed, 15 unresolved discussions (waiting on @Code-Titan and @jacobdeery)

___
*[application/application.py, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zJySo5UoUWhvs3cfM:-M9zJySo5UoUWhvs3cfN:bxdrc1i) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/application.py#L8)):*
> ```
> from .VisualizationArea
> ```

Our Python files should typically be named in `snake_case`. Is there a reason that you've chosen to name the file differently?
___
*[application/application.py, line 30 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zKA-kEAdDEixWc-V8:-M9zKA-kEAdDEixWc-V9:bxmc9ez) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/application.py#L30)):*
> ```
> ········
> ```

Extra whitespace at the start of the line. Please run `tools/format.sh` to autoformat all of the files in this PR.
___
*[application/application.py, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zK8FP9Pd-hB5nY012:-M9zK8FP9Pd-hB5nY013:b-e4sysp) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/application.py#L31)):*
> ```
> qml
> ```
QML
___
*[application/VisualizationArea.py, line 12 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zKd8r8eugZT_ClX0C:-M9zKd8r8eugZT_ClX0D:b6mvmos) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L12)):*
> ```
> it's
> ```
its
___
*[application/VisualizationArea.py, line 13 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zKIbk-QFTMqEY8iaN:-M9zKIbk-QFTMqEY8iaO:b-b50gx3) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L13)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     """
>     A QML-acessible item that will draw the state of the engine. It is a subclass of
>     QQuickPaintedItem, which means it imperatively handles all of it's own events and graphics.
>     """
> ```
</details>


By convention, docstrings should start with a single line summary of the class. See [PEP 257](https://www.python.org/dev/peps/pep-0257/).
___
*[application/VisualizationArea.py, line 15 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zLQ6c9Uu__UYY2scs:-M9zLQ6c9Uu__UYY2sct:b-tz9l0j) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L15)):*
> ```
> #: Flipping this to positive turns on print statments in parts of the code
> ```

1) Comment should have two spaces before the `#`
2) Remove the `:`
3) Use `True` instead of `positive`
___
*[application/VisualizationArea.py, line 24 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zKoi9DyRzhbbJYqCG:-M9zKoi9DyRzhbbJYqCH:b-8oesa7) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L24)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>         # Temporary spec import of the make_engine() function for testing
>         spec = importlib.util.spec_from_file_location('layout_demo.name', \
>                 'C:/Users/Artem Sotnikov/Desktop/design teams/' + \
>                 'topside/topside/visualization/tests/layout_demo.py')
> 
>         layout_demo = importlib.util.module_from_spec(spec)
>         spec.loader.exec_module(layout_demo)
> ```
</details>


This workaround is pretty hard to understand. I definitely think we shouldn't have hardcoded directory paths that will only work on one specific computer. I would suggest just copying the function into this file instead of using importlib.
___
*[application/VisualizationArea.py, line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zLeYq7GU149RzAkDC:-M9zLeYq7GU149RzAkDD:b-9fxz5g) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L35)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         self.engine_instance = None
>         self.scaling_factor = 10
>         self.scaled = False
>         self._color = QColor()
> ```
</details>


Any reason that only `_color` has an underscore?
___
*[application/VisualizationArea.py, line 38 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zLKtS9TRYk4tNBjG2:-M9zLKtS9TRYk4tNBjG3:bqw2122) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L38)):*
> ```
> # Creates instance of test engine
> ```
This comment isn't necessary
___
*[application/VisualizationArea.py, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zKhK69Wo6NQZm2B2s:-M9zKhK76_WEW24hPlXh:b25q0jd) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L41)):*
> ```
> if (self.DEBUG_MODE):
> ```

No parentheses
___
*[application/VisualizationArea.py, line 47 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zLmOE81W4tAMG9dPb:-M9zLmOE81W4tAMG9dPc:b-p04a6g) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L47)):*
> ```
> Overloads the paint method from `QQuickItem`
> ```

First line of docstring should be imperative. This goes for all of the docstrings in this file
___
*[application/VisualizationArea.py, line 56 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zLvFQ7Ud_gddr5IqS:-M9zLvFQ7Ud_gddr5IqT:b-w1392b) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L56)):*
> ```Python
>         painter: QPainter
>             The painter instance which will draw all of the primitives
>         
> ```

Remove newline
___
*[application/VisualizationArea.py, line 60 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zLs3q3y5Y1HWOyx-F:-M9zLs3q3y5Y1HWOyx-G:beiscbv) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L60)):*
> ```
> smol_font
> ```
`small_font`
___
*[application/VisualizationArea.py, line 66 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zM0KO8FESoxpWOUTv:-M9zM0KO8FESoxpWOUTw:b2vlnng) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L66)):*
> ```
> if (self.DEBUG_MODE)
> ```
No parentheses

This is the case for all of the `if` statements; I won't bother leaving comments on all of them, but if statements should not have top-level parentheses in Python
___
*[application/resources/PlumbingPane.qml, line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zMfPC65nxvlCMA1R6:-M9zMfPC65nxvlCMA1R7:b-a08ydm) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/resources/PlumbingPane.qml#L7)):*
> ```QML
> Rectangle {
> 
> 	VisualizationArea {
> ```

Please use spaces rather than tabs


<!-- [...]

2020-06-17 00:32 UTC, Artem-Sotnikov reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42)* status: 1 of 5 files reviewed, 15 unresolved discussions (waiting on @Code-Titan and @jacobdeery)

___
*[application/application.py, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zJySo5UoUWhvs3cfM:-M9zdutf9hWTMt1tSV6E:b-3i9f3v) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/application.py#L8)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> from .VisualizationArea
> ```

Our Python files should typically be named in `snake_case`. Is there a reason that you've chosen to name the file differently?
</blockquote></details>

It technically counts as a file that interacts with the QML and it subclasses from a Qt object. However, it could be done in snake_case and the call to qmlRegisterType would register it in PascalCase for its QML alias. I'm not sure if that would be clearer, but it can be done.
___
*[application/application.py, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zK8FP9Pd-hB5nY012:-M9zfJKCBDDmui_V6rQY:b-dm3euh) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/application.py#L31)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> qml
> ```
QML
</blockquote></details>

it's an imported function from PySide, so I'm not sure what to do here. I could re-define it, but I feel that it would be redundant. 
___
*[application/VisualizationArea.py, line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zLeYq7GU149RzAkDC:-M9zf_h27cjVQtS4c0db:b9nf20l) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L35)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         self.engine_instance = None
>         self.scaling_factor = 10
>         self.scaled = False
>         self._color = QColor()
> ```

Any reason that only `_color` has an underscore?
</blockquote></details>

It's to make sure that it does not clash with the registered color property. I had it as just color at first and it broke. If it's better I can rename it to something else entirely (i. e. graphics_color, color_property). I'm not sure if that's clearer though.


<!-- Sent from Reviewable.io -->

2020-06-17 00:37 UTC, Artem-Sotnikov reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42)* status: 1 of 5 files reviewed, 15 unresolved discussions (waiting on @Code-Titan and @jacobdeery)

___
*[application/application.py, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zK8FP9Pd-hB5nY012:-M9zhAGH3SJOzyZMHIe7:b-pjl51e) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/application.py#L31)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

it's an imported function from PySide, so I'm not sure what to do here. I could re-define it, but I feel that it would be redundant. 
</blockquote></details>

I'll change the comment though


<!-- Sent from Reviewable.io -->

2020-06-17 00:47 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42)* status: 1 of 5 files reviewed, 17 unresolved discussions (waiting on @Code-Titan)

___
*[application/application.py, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zJySo5UoUWhvs3cfM:-M9zhgCqEnD1lZP5SDZX:bfdpz8e) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/application.py#L8)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

It technically counts as a file that interacts with the QML and it subclasses from a Qt object. However, it could be done in snake_case and the call to qmlRegisterType would register it in PascalCase for its QML alias. I'm not sure if that would be clearer, but it can be done.
</blockquote></details>

I agree that the class should be named in PascalCase, but I don't think that the file should be. 
___
*[application/application.py, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zK8FP9Pd-hB5nY012:-M9zhLdL1zxCKpo4uC5W:bi5esvv) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/application.py#L31)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

I'll change the comment though
</blockquote></details>

I'm referring to the capitalization in the comment, not the function.
___
*[application/VisualizationArea.py, line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zLeYq7GU149RzAkDC:-M9ziTnGCxZeFrLkptBz:btk0pkt) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L35)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

It's to make sure that it does not clash with the registered color property. I had it as just color at first and it broke. If it's better I can rename it to something else entirely (i. e. graphics_color, color_property). I'm not sure if that's clearer though.
</blockquote></details>

I think renaming it might be just a tiny bit better - in Python, underscore prefixes are used by convention to denote private member variables and methods, so using that here could be a bit confusing (why is only `_color` private - does that imply the others are public?).
___
*[application/VisualizationArea.py, line 188 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9ziNZ36JviC7AD3U0b:-M9ziNZ36JviC7AD3U0c:b2jx8as) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L188)):*
> ```
> ----------
> ```
Should only have as many characters as `Returns`
___
*[application/VisualizationArea.py, line 200 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9ziLqJEwpoh7Vck-cf:-M9ziLqJEwpoh7Vck-cg:b-26gz1s) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L200)):*
> ```
> Returns
> ```
Parameters


<!-- Sent from Reviewable.io -->

2020-06-17 02:14 UTC, wendi-yu requested changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42)* status: 0 of 5 files reviewed, 19 unresolved discussions (waiting on @Code-Titan, @jacobdeery, and @wendi-yu)

___
*[application/visualization_area.py, line 45 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zsx7L8oJOcqMPSO5A:-M9zsx7L8oJOcqMPSO5B:b-z0pcx8) ([raw file](https://github.com/waterloo-rocketry/topside/blob/27180b5229ab032d114119a2a1aad66665a92bc2/application/visualization_area.py#L45)):*
> ```Python
> class VisualizationArea(QQuickPaintedItem):
>     """
>     A QML-acessible item that will draw the state of the engine. 
> ```

Trailing whitespaces here too, like Jacob said the format.sh script will take care of these as well. Reviewable points them out with red dots if you ever want to check for them :0 
___
*[application/visualization_area.py, line 51 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zu2GS0l4k6oMpcOua:-M9zu2GS0l4k6oMpcOub:bjmseg0) ([raw file](https://github.com/waterloo-rocketry/topside/blob/27180b5229ab032d114119a2a1aad66665a92bc2/application/visualization_area.py#L51)):*
> ```Python
>     """
> 
>     DEBUG_MODE = False  # Flipping this to positive turns on print statments in parts of the code
> ```

I like the debug print mode, seems very useful. Could be useful for logging later on :) 
___
*[application/visualization_area.py, line 135 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA-1xZwBWaM29gWr23F:-MA--v0w9Vfv82KdPAHT:b-akdumd) ([raw file](https://github.com/waterloo-rocketry/topside/blob/27180b5229ab032d114119a2a1aad66665a92bc2/application/visualization_area.py#L135)):*
> ```Python
> 
>             if (not self.scaled):
>                 self.scaled = True
> ```

Is there a reason we’re only scaling on the first call to paint? If it’s an effect that’s intended to be lasting, would it make more sense to do it in the init()?


<!-- Sent from Reviewable.io -->

2020-06-17 03:00 UTC, Artem-Sotnikov reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42)* status: 0 of 5 files reviewed, 19 unresolved discussions (waiting on @Code-Titan, @jacobdeery, and @wendi-yu)

___
*[application/visualization_area.py, line 135 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA-1xZwBWaM29gWr23F:-MA-CI3s4jEyrHOM92D5:bjjzup5) ([raw file](https://github.com/waterloo-rocketry/topside/blob/27180b5229ab032d114119a2a1aad66665a92bc2/application/visualization_area.py#L135)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Is there a reason we’re only scaling on the first call to paint? If it’s an effect that’s intended to be lasting, would it make more sense to do it in the init()?
</blockquote></details>

I could do that, but I think it might make the code a bit more cumbersome. The call to print already has loops that access the relevant data, so scaling it on the spot is more compact. If you still think it should be moved I'll do that.


<!-- Sent from Reviewable.io -->

2020-06-17 03:23 UTC, wendi-yu requested changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42)* status: 0 of 5 files reviewed, 19 unresolved discussions (waiting on @Code-Titan and @jacobdeery)

___
*[application/visualization_area.py, line 135 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA-1xZwBWaM29gWr23F:-MA-DIoA9hHWlOh-wwS9:b-z359d8) ([raw file](https://github.com/waterloo-rocketry/topside/blob/27180b5229ab032d114119a2a1aad66665a92bc2/application/visualization_area.py#L135)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

I could do that, but I think it might make the code a bit more cumbersome. The call to print already has loops that access the relevant data, so scaling it on the spot is more compact. If you still think it should be moved I'll do that.
</blockquote></details>

That's fair - considering how it's a reasonably-sized Python application I wouldn't be hugely concerned about efficiency, but up to you. If you do keep it here maybe pop in a comment that explains this is intentionally a one-time setup. It does make sense for a resize to be here if we implement zoom or other features like that later on :)
___
*[application/visualization_area.py, line 230 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA-I32TBC6LSvr7BfMB:-MA-I32TBC6LSvr7BfMC:b-mrkbu4) ([raw file](https://github.com/waterloo-rocketry/topside/blob/27180b5229ab032d114119a2a1aad66665a92bc2/application/visualization_area.py#L230)):*
> ```Python
>         Set the local color to the given color.
> 
>         Setter for the qml-acessible color property 'color', which is registered by
> ```

QML again?


<!-- Sent from Reviewable.io -->

2020-06-17 12:45 UTC, jacobdeery reviewed
Thanks for all the hard work on this PR. I think it's almost ready, although I do want to still test the packaged executable.

Another general comment: When you push changes that address PR comments, it's best to comment "Done" on the comments that you've addressed. Makes it easier for the reviewers to keep track of what is still open.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-:-MA1IRujEmDLOKXM3mZo:bw3p1mj)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @Code-Titan and @jacobdeery)

___
*[application/resources/PlumbingPane.qml, line 13 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1Hwa0EQPVdUuUjhgZ:-MA1Hwa0EQPVdUuUjhg_:b-8s972k) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/resources/PlumbingPane.qml#L13)):*
> ```QML
>         anchors.centerIn: parent
>     }
> 	
> ```

There's some sort of whitespace on this line (an extra tab or space)
___
*[topside/visualization/tests/layout_demo.py, line 39 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1I1GcEOrgNimNMw33:-MA1I1GcEOrgNimNMw34:b-47pfzk) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/topside/visualization/tests/layout_demo.py#L39)):*
> ```
> "
> ```
Should use single quotes
___
*[application/visualization_area.py, line 48 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1IBH9CTpXInMkNe0i:-MA1IBH9CTpXInMkNe0j:b7hrboe) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L48)):*
> ```
> graphics
> ```
End with period
___
*[application/visualization_area.py, line 170 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1HewsCMbKl2NscVfG:-MA1HewsCMbKl2NscVfH:b-df1wg8) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L170)):*
> ```
> occured
> ```
occurred, and end with a period to be consistent with the other docstrings
___
*[application/visualization_area.py, line 199 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1Hjn4Cpo2te7DRppi:-MA1Hjn4Cpo2te7DRppj:b-nod5lv) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L199)):*
> ```
> data
> ```
end with period
___
*[application/visualization_area.py, line 222 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1HtHX2hg1z-A2Do1R:-MA1HtHX2hg1z-A2Do1S:b-oe7qr0) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L222)):*
> ```
> ·
> ```
Trailing space
___
*[application/visualization_area.py, line 237 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1HpNb0UNeb7_SMrdF:-MA1HpNb0UNeb7_SMrdG:b-7tnjv0) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L237)):*
> ```
> ·
> ```
trailing space


<!-- Sent from Reviewable.io -->

2020-06-17 12:48 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42)* status: 0 of 5 files reviewed, 11 unresolved discussions (waiting on @Code-Titan and @jacobdeery)

___
*[application/visualization_area.py, line 7 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1J46x8gqEkYTuYxo7:-MA1J46x8gqEkYTuYxo8:b-998g4k) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L7)):*
> ```
> # Note: Copied from layout_demo to avoid using importlib
> ```
`Note` should be in all caps (`NOTE`)

I think this comment should actually be right before `make_engine` and with an extra newline before it, so like this:

```
import topside as top


# NOTE: Copied from layout_demo to avoid using importlib
def make_engine():
```


<!-- Sent from Reviewable.io -->

2020-07-01 19:07 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42)* status: 0 of 5 files reviewed, 15 unresolved discussions (waiting on @Code-Titan and @jacobdeery)

___
*[application/visualization_area.py, line 45 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MBAlYWe9HZPRS-Ac1PT:-MBAlYWe9HZPRS-Ac1PU:bo4qcx6) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L45)):*
> ```
> acessible
> ```
accessible
___
*[application/visualization_area.py, line 216 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MBAlSaoCrJFnK_0O3Kr:-MBAlSaoCrJFnK_0O3Ks:bo4qcx6) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L216)):*
> ```
> acessible
> ```
accessible
___
*[application/visualization_area.py, line 231 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MBAlR1JAUZIrjXHkzpv:-MBAlR1JAUZIrjXHkzpw:bo4qcx6) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L231)):*
> ```
> acessible
> ```
accessible
___
*[application/visualization_area.py, line 242 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MBAlOljE5m2ktbiz4si:-MBAlOljE5m2ktbiz4sj:bo4qcx6) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L242)):*
> ```
> acessible
> ```
accessible


<!-- Sent from Reviewable.io -->

2020-07-01 19:22 UTC, Artem-Sotnikov reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42)* status: 0 of 5 files reviewed, 15 unresolved discussions (waiting on @Code-Titan, @jacobdeery, and @wendi-yu)

___
*[application/VisualizationArea.py, line 56 at r1](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zLvFQ7Ud_gddr5IqS:-MBAilKN1ChkiXfw2kwh:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/08f8fb6e271047745360488b46632641e4e43b68/application/VisualizationArea.py#L56)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Remove newline
</blockquote></details>

Done.
___
*[application/visualization_area.py, line 45 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-M9zsx7L8oJOcqMPSO5A:-MBAiLRdCTzfyAMCSBbS:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/27180b5229ab032d114119a2a1aad66665a92bc2/application/visualization_area.py#L45)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Trailing whitespaces here too, like Jacob said the format.sh script will take care of these as well. Reviewable points them out with red dots if you ever want to check for them :0 
</blockquote></details>

Done.
___
*[application/visualization_area.py, line 230 at r2](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA-I32TBC6LSvr7BfMB:-MBAmn5KDxYMaHrZw0rh:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/27180b5229ab032d114119a2a1aad66665a92bc2/application/visualization_area.py#L230)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

QML again?
</blockquote></details>

Done.
___
*[application/visualization_area.py, line 7 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1J46x8gqEkYTuYxo7:-MBAgat93LkZi5XQrEsC:bs7wumb) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L7)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> # Note: Copied from layout_demo to avoid using importlib
> ```
`Note` should be in all caps (`NOTE`)

I think this comment should actually be right before `make_engine` and with an extra newline before it, so like this:

```
import topside as top


# NOTE: Copied from layout_demo to avoid using importlib
def make_engine():
```
</blockquote></details>

Done.
___
*[application/visualization_area.py, line 48 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1IBH9CTpXInMkNe0i:-MBAiVzY6pCcrl5TW1JN:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L48)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> graphics
> ```
End with period
</blockquote></details>

Done.
___
*[application/visualization_area.py, line 170 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1HewsCMbKl2NscVfG:-MBAite_BipJ5v6ky8Xz:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L170)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> occured
> ```
occurred, and end with a period to be consistent with the other docstrings
</blockquote></details>

Done.
___
*[application/visualization_area.py, line 199 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1Hjn4Cpo2te7DRppi:-MBAiwFgCl8rDzbDYhpP:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L199)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> data
> ```
end with period
</blockquote></details>

Done.
___
*[application/visualization_area.py, line 222 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1HtHX2hg1z-A2Do1R:-MBAiytW56VHRiK_tAGa:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L222)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> ·
> ```
Trailing space
</blockquote></details>

Done.
___
*[application/visualization_area.py, line 231 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MBAlR1JAUZIrjXHkzpv:-MBAmly1CDKDE82jDHXr:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L231)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> acessible
> ```
accessible
</blockquote></details>

Done.
___
*[application/visualization_area.py, line 237 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1HpNb0UNeb7_SMrdF:-MBAmoJC5kZv2qLzoOwy:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L237)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> ·
> ```
trailing space
</blockquote></details>

Done.
___
*[application/visualization_area.py, line 242 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MBAlOljE5m2ktbiz4si:-MBAmocz5hDoIVKNmDDX:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L242)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> acessible
> ```
accessible
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-07-01 19:26 UTC, Artem-Sotnikov reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42)* status: 0 of 5 files reviewed, 15 unresolved discussions (waiting on @Code-Titan, @jacobdeery, and @wendi-yu)

___
*[topside/visualization/tests/layout_demo.py, line 39 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MA1I1GcEOrgNimNMw33:-MBAppBb0IbvrWYoMqAW:b-896fix) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/topside/visualization/tests/layout_demo.py#L39)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> "
> ```
Should use single quotes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-07-01 19:45 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @Code-Titan, @jacobdeery, and @wendi-yu)

___
*[application/visualization_area.py, line 242 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MBAlOljE5m2ktbiz4si:-MBAu4SNDhiI6zjBxcgt:bfhqmln) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L242)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2020-07-01 22:47 UTC, Artem-Sotnikov reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jacobdeery)

___
*[application/visualization_area.py, line 45 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MBAlYWe9HZPRS-Ac1PT:-MBBYp_RCxENcKJBOZnl:b-gbz4p3) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L45)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> acessible
> ```
accessible
</blockquote></details>

Should also be correct in the most up-to-date version of the PR.
___
*[application/visualization_area.py, line 242 at r3](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-MBAlOljE5m2ktbiz4si:-MBBXc0yDcMOOU5gAo9D:bhy7puw) ([raw file](https://github.com/waterloo-rocketry/topside/blob/067aca8b8010eeb5a2b4191216e8d44fb5fdfb40/application/visualization_area.py#L242)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

This should be correct in the most up-to-date version of the PR. 


<!-- Sent from Reviewable.io -->

2020-07-01 22:51 UTC, jacobdeery submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, let's do it!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-:-MBBZqcf9uVYWU-JB11l:b-3j1y81)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @jacobdeery)



<!-- Sent from Reviewable.io -->

2020-07-01 22:58 UTC, jacobdeery approved these changes
Nice find

2020-07-02 00:29 UTC, wendi-yu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/topside/42#-:-MBBvIig1MUY6J7tvE1m:b4xxo5c)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @jacobdeery)



<!-- Sent from Reviewable.io -->

2020-07-02 00:29 UTC, merged